// Scans ../benchmarks/*/dart/*.dart for BenchmarkBase subclasses with a
// no-arg constructor and emits bin/run_all.dart with imports + a factory list.
//
// Skipped files:
//   - import 'package:expect/expect.dart'  (SDK-internal, can't resolve)
//   - import 'package:ffi/...' / 'dart:ffi'  (needs prebuilt .so/.dylib)
//   - import 'dart:isolate' (spawns, complicates visualization)
//   - import 'dart:io' (path-dependent IO)
//   - extends AsyncBenchmarkBase (harness is sync-only for now)

import 'dart:io';

const _benchmarksDir = '../benchmarks';
const _outFile = 'bin/run_all.dart';

final _skipImports = <RegExp>[
  RegExp(r"package:expect/"),
  RegExp(r"package:ffi/"),
  RegExp(r"dart:ffi"),
  RegExp(r"dart:isolate"),
  RegExp(r"dart:io"),
  RegExp(r"dart:cli"),
];

class Found {
  final String filePath; // path relative to bench_viz/
  final String alias;
  final List<String> classNames;
  Found(this.filePath, this.alias, this.classNames);
}

void main() async {
  final root = Directory(_benchmarksDir);
  final entries = root
      .listSync()
      .whereType<Directory>()
      .map((d) {
        final inner = Directory('${d.path}/dart');
        if (!inner.existsSync()) return null;
        return inner.listSync().whereType<File>().where(
            (f) => f.path.endsWith('.dart')).toList();
      })
      .whereType<List<File>>()
      .expand((x) => x)
      .toList()
    ..sort((a, b) => a.path.compareTo(b.path));

  final found = <Found>[];
  final usedAliases = <String>{};

  for (final file in entries) {
    final src = file.readAsStringSync();
    if (!src.contains('package:benchmark_harness/benchmark_harness.dart')) {
      continue;
    }
    if (_skipImports.any((r) => r.hasMatch(src))) continue;
    if (RegExp(r"extends\s+AsyncBenchmarkBase").hasMatch(src)) continue;

    // Collect classes that transitively extend BenchmarkBase, in declaration
    // order. We only care about concrete (non-abstract) subclasses.
    final reClass = RegExp(
        r"^(?:abstract\s+)?class\s+([A-Za-z_][A-Za-z0-9_]*)\s+extends\s+([A-Za-z_][A-Za-z0-9_]*)",
        multiLine: true);
    final reAbstract = RegExp(r"^abstract\s+class\s+([A-Za-z_][A-Za-z0-9_]*)",
        multiLine: true);
    final abstracts = <String>{
      for (final m in reAbstract.allMatches(src)) m.group(1)!,
    };
    final benchClasses = <String>{'BenchmarkBase'};
    final allDecls = reClass.allMatches(src).toList();
    var changed = true;
    while (changed) {
      changed = false;
      for (final m in allDecls) {
        final name = m.group(1)!, parent = m.group(2)!;
        if (benchClasses.contains(parent) && !benchClasses.contains(name)) {
          benchClasses.add(name);
          changed = true;
        }
      }
    }

    final concrete = <String>[
      for (final m in allDecls)
        if (benchClasses.contains(m.group(1)) &&
            !abstracts.contains(m.group(1)) &&
            m.group(1) != 'BenchmarkBase')
          m.group(1)!,
    ];

    // For each concrete class, check that there is a no-arg constructor.
    final usable = <String>[];
    for (final name in concrete) {
      final reCtor = RegExp(
          '(?:const\\s+)?$name\\s*\\(\\s*\\)\\s*(?::|\\{|;)');
      if (reCtor.hasMatch(src)) {
        usable.add(name);
      }
    }
    if (usable.isEmpty) continue;

    // Compute alias from path (e.g. benchmarks/Foo/dart/Foo.dart → _foo).
    final stem =
        file.uri.pathSegments.last.replaceAll('.dart', '').toLowerCase();
    var alias = '_$stem';
    var i = 2;
    while (usedAliases.contains(alias)) {
      alias = '_${stem}_$i';
      i++;
    }
    usedAliases.add(alias);

    // Make the import path relative to bench_viz/bin/.
    final rel = '../${file.path}';
    found.add(Found(rel, alias, usable));
  }

  // Emit run_all.dart.
  final sb = StringBuffer();
  sb.writeln('// GENERATED by tool/gen_registry.dart. Do not edit by hand.');
  sb.writeln('// Re-run: dart tool/gen_registry.dart');
  sb.writeln();
  sb.writeln("import 'dart:convert';");
  sb.writeln("import 'dart:io';");
  sb.writeln();
  sb.writeln("import 'package:bench_viz/sampling_harness.dart';");
  sb.writeln(
      "import 'package:benchmark_harness/benchmark_harness.dart';");
  sb.writeln();
  for (final f in found) {
    sb.writeln("import '${f.filePath}' as ${f.alias};");
  }
  sb.writeln();
  sb.writeln('typedef BenchmarkFactory = BenchmarkBase Function();');
  sb.writeln();
  sb.writeln('final _registry = <BenchmarkFactory>[');
  for (final f in found) {
    for (final cls in f.classNames) {
      sb.writeln('  () => ${f.alias}.$cls(),');
    }
  }
  sb.writeln('];');
  sb.writeln();
  sb.writeln(r'''
void main(List<String> args) async {
  var seconds = 2;
  var outDir = 'out';
  var only = <String>{};
  for (var i = 0; i < args.length; i++) {
    final a = args[i];
    if (a == '--seconds' && i + 1 < args.length) seconds = int.parse(args[++i]);
    if (a == '--out-dir' && i + 1 < args.length) outDir = args[++i];
    if (a == '--only' && i + 1 < args.length) only = args[++i].split(',').toSet();
  }

  final results = <Map<String, dynamic>>[];
  for (final factory in _registry) {
    BenchmarkBase b;
    try {
      b = factory();
    } catch (e) {
      stderr.writeln('skip (ctor failed): $e');
      continue;
    }
    if (only.isNotEmpty && !only.contains(b.name)) continue;
    stdout.write('${b.name.padRight(40)} ... ');
    final harness = SamplingHarness(b, duration: Duration(seconds: seconds));
    try {
      harness.run();
    } catch (e) {
      stdout.writeln('FAILED: $e');
      continue;
    }
    final json = harness.toJson();
    results.add(json);
    final safe = b.name.replaceAll(RegExp(r'[^A-Za-z0-9_.-]'), '_');
    final f = await File('$outDir/$safe.json').create(recursive: true);
    await f.writeAsString(const JsonEncoder.withIndent('  ').convert(json));
    stdout.writeln('${harness.samples.length} samples '
        '(iters/sample=${harness.iterationsPerSample})');
  }

  await File('$outDir/all.json')
      .writeAsString(const JsonEncoder.withIndent('  ').convert(results));
  stdout.writeln('\nWrote ${results.length} benchmarks to $outDir/.');
}
''');

  await File(_outFile).writeAsString(sb.toString());
  stdout.writeln('Wrote $_outFile with ${found.length} files / '
      '${found.fold<int>(0, (a, f) => a + f.classNames.length)} benchmarks.');
}
